[package]
name = "snake"
version = "0.1.0"
authors = ["Joshua Kidd <kidd.josh.343@gmail.com>"]

[dependencies]
piston = "0.17"
piston2d-graphics = "0.13.0"
pistoncore-glutin_window = "0.20.0"
piston2d-opengl_graphics = "0.23.0"
